"""NewsfeedDemo — M0 validation agent.

Calls llm_driver once with AGENT.md body as system prompt, writes a single
markdown report. One_shot. Run is complete when report is written.

Config via env:
  NEWSFEED_POOL      rate_limit pool name (default: "openai")
  NEWSFEED_MODEL     model name (falls back to TFE_MODEL env, then "gpt-4o-mini")
"""
from __future__ import annotations

import logging
import os
from datetime import datetime

log = logging.getLogger(__name__)


class NewsfeedDemo:
    def __init__(self, ctx) -> None:
        self.ctx = ctx

    async def run_once(self) -> dict:
        pool = os.environ.get("NEWSFEED_POOL", "openai")
        model = (
            os.environ.get("NEWSFEED_MODEL")
            or os.environ.get("TFE_MODEL")
            or "gpt-4o-mini"
        )

        system_prompt = (self.ctx.body or "").strip()
        if not system_prompt:
            return {"ok": False, "error": "AGENT.md body empty — no system prompt"}

        log.info("newsfeed_demo: calling llm_driver pool=%s model=%s", pool, model)
        try:
            resp = await self.ctx.bus.request(
                "llm_driver",
                {
                    "op": "run_turn",
                    "system_prompt": system_prompt,
                    "messages": [{"role": "user", "content": "生成今日 A 股 3 条热点新闻"}],
                    "pool": pool,
                    "model": model,
                    "temperature": 0.3,
                    "max_iterations": 1,
                    "llm_timeout": 120.0,
                    "strip_thinking_blocks": True,
                },
                timeout=150.0,
            )
        except Exception as e:
            log.exception("newsfeed_demo: bus.request llm_driver raised")
            return {"ok": False, "error": f"bus.request raised: {e}"}

        if not resp.get("ok"):
            log.error("newsfeed_demo: llm_driver failed: %s", resp.get("error"))
            return {"ok": False, "error": resp.get("error") or "llm_driver not ok"}

        content = resp.get("content") or ""
        usage = resp.get("usage") or {}

        report_dir = self.ctx.agent_dir / "reports"
        report_dir.mkdir(parents=True, exist_ok=True)
        today = datetime.now().strftime("%Y-%m-%d")
        # Use timestamp suffix if already exists (multi-run same day)
        stamp = datetime.now().strftime("%H%M%S")
        path = report_dir / f"{today}-{stamp}.md"

        header = (
            f"# A 股热点新闻 — {today}\n\n"
            f"_Generated by yuxu/newsfeed_demo (M0 validation)_\n\n"
            f"- Model: `{model}`\n"
            f"- Pool: `{pool}`\n"
            f"- Prompt tokens: {usage.get('prompt_tokens', 0)}\n"
            f"- Completion tokens: {usage.get('completion_tokens', 0)}\n"
            f"- Iterations: {resp.get('iterations', 1)}\n"
            f"- Stop reason: `{resp.get('stop_reason', 'unknown')}`\n\n"
            f"---\n\n"
        )
        path.write_text(header + content + "\n", encoding="utf-8")

        log.info("newsfeed_demo: report written to %s", path)
        return {
            "ok": True,
            "report_path": str(path),
            "content_preview": content[:200],
            "usage": usage,
        }
